
path: '/content/gdrive/MyDrive/../Shareddrives/PEF OT23/Documentaci√≥n/Ejemplo de YOLO/training-format/' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: alpaca
